name: platformio
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get date
        run: |
          echo "now=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          echo "${{ env.now }}"
          
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'platformio'
          repository: 'platformio-docs'

      - name: Install and Build
        run: |
          cd platformio-docs
          sudo apt install python3-sphinx
          pip install sphinx_rtd_theme platformio sphinx-notfound-page sphinx_copybutton
          make html
          
      - name: zip
        run: cd platformio-docs/_build && zip -r pio.zip *
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "pio_${{ env.now }}"
          release_name: platformio
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./platformio-docs/_build/pio.zip
          asset_name: pio.zip
          asset_content_type: application/zip
